version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update -y
            apt-get install -y cmake \
            build-essential \
            libcurl4-openssl-dev \
            python3
      - run:
          name: Build bam
          command: |
            git clone https://github.com/matricks/bam.git ~/bam
            cd ~/bam/
            git reset --hard f012dd9a3e38295b8a45af5a101d29573381f169
            ./make_unix.sh
      - run:
          name: Build DDNet++ with bam (debug)
          command: |
            ~/bam/bam server_debug
            ./DDNetPP_d shutdown
      - run:
          name: Build DDNet++ with bam (release)
          command: |
            ~/bam/bam server_release
            ./DDNetPP shutdown
      - run:
          name: Build DDNet++ with cmake
          command: |
            mkdir -p build
            cd build
            cmake ..
            make
            ./DDNetPP shutdown
