version: 2
defaults: &defaults
  working_directory: ~/DDNetPP/DDNetPP
  docker:
    - image: buildpack-deps:stretch

defignore: &defignore
  filters:
    branches:
      ignore:
        - /.*\.tmp/

jobs:
  build:
    <<: *defaults
    parallelism: 1

    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y build-essential \
            python3 \
            libcurl4-openssl-dev
      # Compile
      - run: |
          ./bam server_release
          ./bam server_debug
      - persist-to-workspace:
          root: ./
          paths: ./*

workflows:
    version: 2
    build_and_test:
        jobs:
            - build:
                <<: *defignore
